version: "3"
services:
  broker:
    container_name: mqtt
    image: dendebaiano/suricato-mqtt:v1.6.9
#    volumes:
#      - ./mosquitto:/etc/mosquitto
    networks:
      - rede-docker
    ports:
      - "1883:1883"
      - "9001:9001"
  
  node-red:
    container_name: node-red
    image: dendebaiano/suricato-nodered:1.1
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    user: "0"
    networks:
      - rede-docker
    depends_on:
      - broker

  api:
    container_name: api
    image: dendebaiano/suricato-api:2.5
    ports:
     - 3000:3000
    networks:
     - rede-docker
    depends_on:
    - broker
    - node-red

  wd-bot:
    container_name: wd-bot
    image: dendebaiano/suricato-wd-bot:1.0
    ports:
     - 6969:6969
    networks:
     - rede-docker
    depends_on:
    - api
    - node-red
    - broker
  
  main-bot:
    container_name: main-bot
    image: dendebaiano/suricato-main-bot:1.0
    ports:
     - 6868:6868
    networks:
     - rede-docker
    depends_on:
    - api
    - node-red
    - broker

volumes:
  node-red-data:

networks:
  rede-docker:
    driver: bridge
