version: "3"
services:
  broker:
    container_name: mqtt
    image: dendebaiano/suricato-mqtt:1.0.0
    volumes:
      - $(PWD)/mosquitto:/etc/mosquitto
    networks:
      - rede-docker
    ports:
      - "1883:1883"
      - "9001:9001"
  
  node-red:
    container_name: node-red
    image: dendebaiano/suricato-nodered:1.1
    ports:
      - "1880:1880"
    volumes:
      - node-red-data:/data
    user: "0"
    networks:
      - rede-docker
    depends_on:
      - broker

  api:
    container_name: api
    image: dendebaiano/suricato-api:1.1
    ports:
     - 3000:3000
    networks:
      - rede-docker
    depends_on:
     - broker
     - node-red

volumes:
  node-red-data:

networks:
  rede-docker:
    driver: bridge
